FROM zhuzilin/slime:latest AS slime

RUN curl -LsSf https://astral.sh/uv/install.sh | sh

RUN rm -rf /root/Megatron-LM
WORKDIR /root/Megatron-LM
# COPY ./Megatron-LM /root/Megatron-LM

# RUN pip install -e .

WORKDIR /root/slime
# COPY pyproject.toml and setup.py and requirements.txt
COPY pyproject.toml setup.py requirements.txt README.md LICENSE ./
COPY VeOmni/pyproject.toml VeOmni/setup.py VeOmni/requirements.txt VeOmni/README.md VeOmni/LICENSE /root/slime/VeOmni/
COPY VeOmni/veomni/__init__.py /root/slime/VeOmni/veomni/__init__.py
# install dependencies
# ENV UV_SYSTEM_PYTHON=1
ENV SETUPTOOLS_SCM_PRETEND_VERSION="0.0.0"
ENV UV_PROJECT_ENVIRONMENT=/usr
ENV PIP_BREAK_SYSTEM_PACKAGES=1
ENV UV_LINK_MODE=copy

RUN uv sync --inexact --no-group docker-override
# RUN pip install -e .
# copy the rest of the code

# RUN mkdir -p /secrets
RUN --mount=type=secret,id=wandb_key \
  /usr/local/bin/wandb login $(cat /run/secrets/wandb_key)

RUN --mount=type=secret,id=huggingface_key \
  /usr/local/bin/huggingface-cli login --token $(cat /run/secrets/huggingface_key)

COPY . .

# hf download Qwen/Qwen3-0.6B --local-dir /root/Qwen3-0.6B

# # Download training dataset (dapo-math-17k)
# hf download --repo-type dataset zhuzilin/dapo-math-17k --local-dir /root/dapo-math-17k

# # Download evaluation dataset (aime-2024)
# hf download --repo-type dataset zhuzilin/aime-2024 --local-dir /root/aime-2024



# RUN uv pip install --no-deps --no-build-isolation --force-reinstall -e .